### PR TITLE
Exams by Kyryl Kozarezov IM-33

### PR DESCRIPTION
**Pull request by Kiryaoo**

### CODE REVIEW

**Comment by namanica** [comment]
good job has been done!

**Comment by alomj** [comment]
i agree with all comits

**Comment by Adaptolog** [comment]
Great👌

**Comment by yur-ochka** [comment]
looked through all of the commits and i like it!

**Comment by D-Vasylchenko** [comment]
nice work, everything every step is well explained

**Comment by D-Vasylchenko** [comment]
nice work, everything every step is well explained

**Comment by nikama-s** [comment]
Great, neat code!

**Pull request closed without merging**
