### PR TITLE
Exams Aryna Babanina IM-33

### PR DESCRIPTION
**Pull request by nevsetakpohano**

### CODE REVIEW

**Comment by namanica** [comment]
good job has been done!

**Comment by DavidkJun** [comment]
i have reviewed the changes, and i agree with all the commits

**Comment by nikama-s** [comment]
i agree with all commits, great job!

**Comment by yur-ochka** [comment]
Looked through all of the commits and found them really good!!

**Comment by Kiryaoo** [comment]
Having analyzed these comites, I can say that a good job has been done.

**Pull request closed without merging**
