### PR TITLE
Exams by Maslo Veronika, IM-33

### PR DESCRIPTION
**Pull request by nikama-s**
Done:
day.js, filter.js, month.js, password.js, random.js, ip.js, longest.js, sample.js, quotes.js, validate.js, types.js, split.js, shuffle.js and section.js

### CODE REVIEW

**Comment by namanica** [comment]
good job has been done!

**Comment by alomj** [comment]
you have done a great job!

**Comment by yur-ochka** [comment]
Looked through everything and I like it!

**Comment by Kiryaoo** [comment]
Very good job, agree with all coments

**Comment by D-Vasylchenko** [comment]
I reviewed all changes and totally agree with them

**Comment by DavidkJun** [comment]
i agree with all commits that's been done

**Comment by nevsetakpohano** [comment]
Your changes are so well committed. You've done such a great job!

**Pull request closed without merging**
